### ISSUE TITLE
API

### ISSUE THREAD

**Issue by meetgyn** [olivsec/loboguara#1]
Bom dia jonathan.
Em primeiro lugar gostei muito da sua solução.
Estou aqui tentando instalar para testar porem surgiram algumas duvidas.  Estou com dificuldades de entender como resolver essa questão no config
API_URL,, , - API_ACCESS_TOKEN 
Outra duvida seria com relação aos dominios allowed, Aqui seria o meu dominio de acesso externo tipo meuserverguara.com?
![image](https://github.com/user-attachments/assets/31075789-da5f-45bd-a507-fcea551c54af)

**Comment by Ocaminhante** [comment]
Olá também achei estranho mas na documentação tem o tópico para gerar a API neste link https://loboguara.olivsec.com.br/docs/api_key_generate.html

**Comment by meetgyn** [comment]
> Olá também achei estranho mas na documentação tem o tópico para gerar a API neste link https://loboguara.olivsec.com.br/docs/api_key_generate.html

Sim, eu dei uma olhada porem aqui não consigo fazer a instalação pra depois gerar a key como explica neste link. Sem a key não ha instalação

**Comment by Jetrom17** [comment]
> Sim, agora entendi. Falta de atenção de minha parte. Consegui gerar o token, agora vamos testar a instalação

> [!note]
> Se estiver tudo certo, por favor, feche como concluído. 🤝

**Comment by meetgyn** [comment]
Consegui realizar toda instalação sem erros, porem ao tentar acessar a aplicação, ela não abre. E so me aparece esta tela de erro

![image](https://github.com/user-attachments/assets/dbc2b726-2ff4-40b4-a007-714a44fa14c8)

**Comment by Jetrom17** [comment]
> ![image](https://github.com/user-attachments/assets/dbc2b726-2ff4-40b4-a007-714a44fa14c8)

Verifique se tem algum firewall, porta ou problema específico do Flask, responsável por rodar esse servidor. 
As entradas estão mal formatadas e não me parece ser http. Por isso código 400.

**Comment by rafaelsupport** [comment]
> Consegui realizar toda instalação sem erros, porem ao tentar acessar a aplicação, ela não abre. E so me aparece esta tela de erro
> 
> ![image](https://private-user-images.githubusercontent.com/3695608/381747438-dbc2b726-2ff4-40b4-a007-714a44fa14c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MTM1NjcsIm5iZiI6MTczMDkxMzI2NywicGF0aCI6Ii8zNjk1NjA4LzM4MTc0NzQzOC1kYmMyYjcyNi0yZmY0LTQwYjQtYTAwNy03MTRhNDRmYTE0YzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDZUMTcxNDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE4ZDlkOTJkNjRhOTA0Nzg3ZTJmYWU5NTdjYTAzYjcwNzRiN2FmNjg2YWY4Zjg3NDcxNTZjNDMxYTM2YzNmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4pqPVXwzCYCx7_R_csM-ja8oVvRBlU86vj5LJGS1iFs)

também estou com esse problema
só acesso com HTTP
conseguiu alguma solução?

**Comment by Jetrom17** [comment]
Vocês estão seguindo o tutorial, documentação, certo? Pois o projeto foi testado antes de ser lançado. Para confirmar, isso funcionou no meu.

**Comment by Jetrom17** [comment]
@rafaelsupport e @meetgyn descobri o que vocês estão estranhando. Isso não é um problema. Se acessado `o.o.o.o` o navegador irá informar que não é seguro acessar por esse endereço. Então o log é informado com caracteres por conta da configuração no Flask:

```bash
warnings.warn(
127.0.0.1 - - [08/Nov/2024 10:57:39] code 400, message Bad request version ('\\x15\\x03Í\\x9fðÀãJ÷Î)Æ\\x87')

[...]
```
![print2](https://github.com/user-attachments/assets/bc1ee858-652f-43e8-93c1-511d7f303406)

Mas isso não impede o funcionamento ou interação futura.

![print1](https://github.com/user-attachments/assets/b560becd-dfbd-49bd-98b7-6f528bf6fbf1)

Recomendo acessar pelo endereço: `localhost`. 

Repito, se estiver como concluído, feche e marque como um @meetgyn.
https://github.com/olivsec/loboguara/issues/1#issuecomment-2448338657

**Comment by rafaelsupport** [comment]
> @rafaelsupport e @meetgyn descobri o que vocês estão estranhando. Isso não é um problema. Se acessado `o.o.o.o` o navegador irá informar que não é seguro acessar por esse endereço. Então o log é informado com caracteres por conta da configuração no Flask:
> 
> ```shell
> warnings.warn(
> 127.0.0.1 - - [08/Nov/2024 10:57:39] code 400, message Bad request version ('\\x15\\x03Í\\x9fðÀãJ÷Î)Æ\\x87')
> 
> [...]
> ```
> 
> ![print2](https://private-user-images.githubusercontent.com/72875404/384395120-bc1ee858-652f-43e8-93c1-511d7f303406.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjkxNjgsIm5iZiI6MTczMTMyODg2OCwicGF0aCI6Ii83Mjg3NTQwNC8zODQzOTUxMjAtYmMxZWU4NTgtNjUyZi00M2U4LTkzYzEtNTExZDdmMzAzNDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDEyNDEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYzM3MWQ1MTc4MTBkYTkwNjYxOGFjY2M1OGMwMDBmY2NmZDYyYjFhNWEzMWQxM2UxNDc4MTU5NTUwYWEwYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZThw969hW6WVR1NcJE7miYAqhiDKo2vUBJVvRKavzOE)
> 
> Mas isso não impede o funcionamento ou interação futura.
> 
> ![print1](https://private-user-images.githubusercontent.com/72875404/384395098-b560becd-dfbd-49bd-98b7-6f528bf6fbf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjkxNjgsIm5iZiI6MTczMTMyODg2OCwicGF0aCI6Ii83Mjg3NTQwNC8zODQzOTUwOTgtYjU2MGJlY2QtZGZiZC00OWJkLTk4YjctNmY1MjhiZjZmYmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDEyNDEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNjcxZmMzMmZkNjRjZjc5ZjNkMzM5ZjBkZDBkYzQ1MDU0MDAzNmI0NGE4YzA1Mzg2ZTE1YjVkNzU5NTE4OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8DNJd9K_AXXKnojInlPItWWScaeCz5IQHql920C3cmQ)
> 
> Recomendo acessar pelo endereço: `localhost`.
> 
> Repito, se estiver como concluído, feche e marque como um @meetgyn. [#1 (comment)](https://github.com/olivsec/loboguara/issues/1#issuecomment-2448338657)

tranquilo
na verdade eu não estava acessando com `0.0.0.0`, nem `localhost` e nem `127.0.0.1`
eu estava acessando a partir de uma outra máquina já da rede
obs: projeto instalado num **red hat 9.4**
de qualquer forma, não é um problema para mim acessar apenas com http://ip:7405 ao invés de https://ip:7405, o importante é que rodou

**Comment by Jetrom17** [comment]
@meetgyn se está resolvido, por favor, feche a `issue`. 🤝

**Comment by meetgyn** [comment]
Projeto foi abandonado?
